wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.17.7
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1724721669
    t:
      1:
      - 55
      - 86
      - 95
      - 105
      2:
      - 55
      - 86
      - 95
      - 105
      3:
      - 23
      4: 3.11.3
      5: 0.17.7
      8:
      - 3
      - 5
      9:
        2: langchain
      13: windows-amd64
